language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - composer self-update
  - composer install --dev --no-interaction

script: php vendor/bin/phpunit

after_script:
  - php vendor/bin/coveralls -v
